routes/cliente.py
from flask import Blueprint, render_template, request, url_for, redirect
from config import db
from models.model import Cliente

# CRIANDO VARIÁVEL DE ROTA BP
cliente_bp = Blueprint("cliente", __name__)

@cliente_bp.route("/")
def lista_clientes():
    page = "Clientes"
    title = "Lista de clientes"
    clientes = Cliente.query.all()
    return render_template("lista_clientes.html", page=page, title=title, clientes=clientes)
  
  
@cliente_bp.route("/novo")
def form_novo_cliente():
    page = "Clientes"
    title = "Novo cliente"
    return render_template("novo_cliente.html", page=page, title=title)
  
  
@cliente_bp.route("/cadastra", methods=["POST", "GET"])
def cadastra_cliente():
    
    if request.method == "POST":
        nome = request.form["nome"]
        email = request.form["email"]
        fone = request.form["fone"]
        cpf_cnpj = request.form["cpf_cnpj"]
        logra = request.form["logra"]
        cep = request.form["cep"]
        bairro = request.form["bairro"]
        comple = request.form["comple"]
        cidade = request.form["cidade"]
        uf = request.form["uf"]
        status = request.form["status"]
        
        try:
            new_cliente = Cliente(
                nome, email, fone, cpf_cnpj, logra, cep, bairro, comple, cidade, uf, status
            )
            
            db.session.add(new_cliente)
            db.session.commit()
            msg = "Cadastro efetuado com sucesso!"
            alert = "success"
            return redirect(url_for('cliente.form_novo_cliente', msg=msg, alert=alert))
            
        except Exception as e:
            db.session.rollback()
            msg = f"Não foi possível cadastrar - Erro {str(e)}"
            alert = "danger"
            return redirect(url_for('cliente.form_novo_cliente', msg=msg, alert=alert))
 
 
@cliente_bp.route("/<int:id_cliente>/editar")
def form_editar_cliente(id_cliente):
    page = "Clientes"
    title = "Alterar dados"
    msg = ""
    alert = ""
    cliente = Cliente.query.get(id_cliente)
    if not cliente:
        msg = "O cliente selecionado não existe, selecione um cliente válido."
        alert = "warning"
        return  redirect(url_for('cliente.lista_clientes', msg=msg, alert=alert))
    
    return render_template("editar_cliente.html", page=page, title=title, cliente=cliente, id_cliente=id_cliente)
  
  
@cliente_bp.route("/atualiza", methods=["POST"])
def atualiza_cliente():
    if request.method == "POST":
        id_cliente = request.form["id_cliente"]
        cli = Cliente.query.get(id_cliente)
        
        if cli:
            nome = request.form["nome"]
            email = request.form["email"]
            fone = request.form["fone"]
            cpf_cnpj = request.form["cpf_cnpj"]
            logra = request.form["logradouro"]
            cep = request.form["cep"]
            bairro = request.form["bairro"]
            comple = request.form["complemento"]
            cidade = request.form["cidade"]
            uf = request.form["uf"]
        
            try:
                cli.nome = nome
                cli.email = email
                cli.fone = fone
                cli.cpf_cnpj = cpf_cnpj
                cli.logradouro = logra
                cli.cep = cep
                cli.bairro = bairro
                cli.complemento = comple
                cli.cidade = cidade
                cli.uf = uf
                
                db.session.commit()
                msg = "Dados atualizados com sucesso!"
                alert = "success"
                return redirect(url_for('cliente.lista_clientes', msg=msg, alert=alert))
                
            except Exception as e:
                db.session.rollback()
                msg = f"Não foi possível atualizar - Erro {str(e)}"
                alert = "danger"  
                return redirect(url_for('cliente.lista_clientes', msg=msg, alert=alert))
                
   
@cliente_bp.route("/<int:id_cliente>/delete")
def delete(id_cliente):
    cliente = Cliente.query.get(id_cliente)
    
    if not cliente:
        msg = "O cliente que você tentou excluir não existe, selecione um cliente válido."
        alert = "warning"
        return  redirect(url_for('cliente.lista_clientes', msg=msg, alert=alert))
    
    else:
        try:
            db.session.delete(cliente)
            db.session.commit()
            msg = "Cliente excluido com sucesso!"
            alert = "success"
            return redirect(url_for('cliente.lista_clientes', msg=msg, alert=alert))
            
        except Exception as e:
            db.session.rollback()
            msg = f"Não foi possível excluir este cliente - Erro {str(e)}"
            alert = "danger"  
            return redirect(url_for('cliente.lista_clientes', msg=msg, alert=alert))   

routes/home.py
from flask import Blueprint, render_template

# CRIANDO VARIÁVEL DE ROTA BP
home_bp = Blueprint("home", __name__)


@home_bp.route("/")
def home():
    page = "Início"
    title = "Visão geral"
    return render_template("home.html", title=title, page=page)

routes/perfil.py
from flask import Blueprint, render_template, request, redirect, url_for
from models.model import User
from config import db

# CRIANDO VARIÁVEL DE ROTA BP
perfil_bp = Blueprint("perfil", __name__)


@perfil_bp.route("/")
def lista_perfil():
    ...


@perfil_bp.route("/<string:nome_perfil>")
def perfil_view(nome_perfil):
    page = "Perfil"
    title = "Visualizando perfil"
    return render_template("perfil.html", page=page, title=title)
    

@perfil_bp.route("/novo")
def form_novo_perfil():
    page = "Perfil"
    title = "Novo usuário"
    return render_template("novo_user.html", page=page, title=title)
    

@perfil_bp.route("/cadastra", methods=["POST", "GET"])
def cadastra_perfil():
    if request.method == "POST":
        nick = request.form["nick"]
        nome = request.form["nome"]
        sobrenome = request.form["sobrenome"]
        email = request.form["email"]
        fone = request.form["fone"]
        func = request.form["func"]
        foto = "caminho_da_foto"
        senha1 = request.form["senha1"]
        senha2 = request.form["senha2"]

        verifica_email = User.query.filter_by(email=email).first()

        if not senha1 == senha2:
            msg = "Senhas não coincidem"
            alert = "danger"
            return redirect(url_for('perfil.form_novo_perfil', msg=msg, alert=alert))
        
        elif verifica_email:
            msg = "O email inserido já está em uso"
            alert = "danger"
            return redirect(url_for('perfil.form_novo_perfil', msg=msg, alert=alert))

        else:
            try:
                new_perfil = User(
                    nick, email, nome, sobrenome, func, fone, foto, senha1
                )

                db.session.add(new_perfil)
                db.session.commit()

                msg = "Usuário cadastrado com sucesso!"
                alert = "success"
                return redirect(url_for('perfil.form_novo_perfil', msg=msg, alert=alert))
            
            except Exception as e:
                db.session.rollback()
                msg = "Não foi possível cadastrar, contate o desenvolvedor."
                alert = "danger"
                return redirect(url_for('perfil.form_novo_perfil', msg=msg, alert=alert))


@perfil_bp.route("/<int:id_perfil>/editar")
def form_editar_perfil(id_perfil):
    ...


@perfil_bp.route("/atualiza", methods=["POST"])
def atualiza_perfil():
    ...


@perfil_bp.route("/<int:id_perfil>/delete")
def delete(id_perfil):
    ...
    

routes/projeto.py
from flask import Blueprint, render_template, request, url_for, redirect
from config import db
from models.model import Cliente, Projeto

# CRIANDO VARIÁVEL DE ROTA BP
projeto_bp = Blueprint("projeto", __name__)

@projeto_bp.route("/")
def lista_projetos():
    page = "Projetos"
    title = "Listando projetos"
    projetos = Projeto.query.all()
    return render_template("lista_projetos.html", page=page, title=title, projetos=projetos)
    
    
@projeto_bp.route("/novo")
def form_novo_projeto():
    page = "Projetos"
    title = "Novo projeto"
    count = Cliente.query.count()
    clientes = Cliente.query.all()
    if count == 0:
      msg = "Não há clientes cadastrados, cadastre um cliente para cadastrar um projeto."
      alert = "warning"
      return redirect(url_for("projeto.lista_projetos", msg=msg, alert=alert))
    return render_template("novo_projeto.html", page=page, title=title, clientes=clientes)
    
    
@projeto_bp.route("/cadastra", methods=["POST", "GET"])
def cadastra_projeto():
    if request.method == "POST":
        titulo = request.form["nome"]
        tipo = request.form["tipo"]
        tec = request.form["tec"]
        desc = request.form["desc"]
        valor = request.form["valor"]
        metodo_pag = request.form["metodo_pag"]
        data = request.form["data"]
        status = request.form["status"]
        dono_proj = request.form["solic"]
        
        try:
            new_projeto = Projeto(
                titulo, tipo, tec, desc, valor, metodo_pag, data, status, dono_proj
            )
            db.session.add(new_projeto)
            db.session.commit()
            msg = f"Novo projeto {titulo} cadastrado com sucesso!"
            alert = "success"
            return redirect(url_for('projeto.form_novo_projeto', msg=msg, alert=alert))
            
        except Exception as e:
            db.session.rollback()
            msg = f"Não foi possível cadastrar o projeto <strong>{titulo}</strong> - Erro {str(e)}"
            alert = "danger"
            return redirect(url_for('cliente.form_novo_projeto', msg=msg, alert=alert))
           
    
    
@projeto_bp.route("/<int:id_projeto>/editar")
def form_editar_projeto(id_projeto):
    page = "Projetos"
    title = "Alterar dados"
    projeto = Projeto.query.get(id_projeto)
    clientes = Cliente.query.all()
    
    if not projeto:
        msg = "O projeto selecionado não existe, selecione um projeto válido."
        alert = "warning"
        return  redirect(url_for('projeto.lista_projetos', msg=msg, alert=alert))
    
    return render_template("editar_projeto.html", page=page, title=title, projeto=projeto, clientes=clientes)
    
    
@projeto_bp.route("/atualiza", methods=["POST", "GET"])
def atualiza_projeto():
    if request.method == "POST":
        id_projeto = request.form["id_projeto"]
        proj = Projeto.query.get(id_projeto)
        
        if proj:
            titulo = request.form["titulo"]
            tipo = request.form["tipo"]
            tec = request.form["tec"]
            desc = request.form["desc"]
            valor = request.form["valor"]
            metodo_pag = request.form["metodo_pag"]
            data = request.form["data"]
            status = request.form["status"]
            dono_proj = request.form["dono_proj"]
            
            try:
                proj.titulo = titulo
                proj.tipo = tipo
                proj.tecnologia = tec
                proj.detalhes = desc
                proj.valor = valor
                proj.metodo_pag = metodo_pag
                proj.data_entrega = data
                proj.status = status
                proj.cliente_id = dono_proj
                
                db.session.commit()
                msg = "Dados atualizados com sucesso!"
                alert = "success"
                return redirect(url_for('projeto.lista_projetos', msg=msg, alert=alert))
            
            except Exception as e:
                db.session.rollback()
                msg = f"Não foi possível atualizar - Erro {str(e)}"
                alert = "danger"    
                return redirect(url_for('projeto.lista_projetos', msg=msg, alert=alert))
           
        
    
    
@projeto_bp.route("/<int:id_projeto>/delete")
def delete(id_projeto):
    projeto = Projeto.query.get(id_projeto)
    
    if not projeto:
        msg = "O projeto que você tentou excluir não existe, selecione um projeto válido."
        alert = "warning"
        return  redirect(url_for('projeto.lista_projetos', msg=msg, alert=alert))
    
    else:
        try:
            db.session.delete(projeto)
            db.session.commit()
            msg = "Projeto excluido com sucesso!"
            alert = "success"
            return redirect(url_for('projeto.lista_projetos', msg=msg, alert=alert))
            
        except Exception as e:
            db.session.rollback()
            msg = f"Não foi possível excluir este cliente - Erro {str(e)}"
            alert = "danger"  
            return redirect(url_for('projeto.lista_projetos', msg=msg, alert=alert))

templates/lista_clientes.html
{% extends "base.html" %}

{% block content %}

{% if request.args["msg"] %}
<div class="alert alert-{{request.args['alert']}} alert-dismissible text-white opacity-8" role="alert">
	<span class="text-sm">{{request.args["msg"]}}</span>
	<button type="button" class="btn-close text-lg py-3 opacity-10" data-bs-dismiss="alert" aria-label="Close">
	  <span aria-hidden="true">&times;</span>
	</button>
</div>
{% endif %}

<div class="row">
    <div class="col-12">
        <div class="card my-4">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
				<div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
					<h6 class="text-white text-capitalize ps-3">Exibe 10 registros por página</h6>
				</div>
            </div>
            <div class="card-body px-0 pb-2">
				<div class="table-responsive p-0 text-center">
			  
					{% if clientes|length == 0 %}
					<h6 class="text-secondary">Não há nada a exibir ainda, clique no botão para inserir</h6>
					<a href="{{url_for('cliente.form_novo_cliente')}}" class="btn btn-info">novo cliente</a>
					{% else %}
				
					<table class="table align-items-center mb-0">
						<thead>
							<tr>
							<th class="text-uppercase text-secondary text-s font-weight-bolder opacity-7">ID</th>
							<th class="text-uppercase text-secondary text-s font-weight-bolder opacity-7">Cliente</th>
							<th class="text-uppercase text-secondary text-s font-weight-bolder opacity-7">Telefone</th>
							<th class="text-center text-uppercase text-secondary text-s font-weight-bolder opacity-7">Status</th>
							<th class="text-center text-uppercase text-secondary text-s font-weight-bolder opacity-7">Ações</th>
							</tr>
						</thead>
						<tbody>
							{% for cli in clientes %}
							<tr>
								<td>
									<div class="">
										<div class="">
											<span class="">{{ cli.id_cliente }}</span>
										</div>
									</div>
								</td>
								<td>
									<div class="">
										<div class="">
											<span class="text-dark font-weight-bold mb-0">{{ cli.nome }}</span>
											<p class="text-sm text-secondary mb-0">{{ cli.email }}</p>
										</div>
									</div>
								</td>
								<td>
									<p class="text-s font-weight-bold mb-0">{{ cli.fone }}</p>
									<p class="text-sm text-secondary mb-0">{{ cli.cidade }}</p>
								</td>
								<td class="align-middle text-center text-sm">
									<span class="badge badge-sm bg-gradient-{%if cli.status == 'regular'%}success{%else%}warning{%endif%}">{{ cli.status }}</span>
								</td>
								<td class="align-middle text-center">
									<a href="{{ url_for('cliente.form_editar_cliente', id_cliente=cli.id_cliente) }}" title="Alterar dados">
										<span class="material-symbols-outlined text-dark text-lg">edit_square</span>
									</a>
									<span class="material-symbols-outlined text-info text-lg" data-bs-toggle="modal" data-bs-target="#staticBackdrop{{cli.id_cliente}}" style="cursor:pointer;" title="Ver detalhes">visibility</span>
								</td>
							</tr>

							<!-- Modal -->
							<div class="modal fade" id="staticBackdrop{{cli.id_cliente}}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
								<div class="modal-dialog">
									<div class="modal-content">
										<div class="modal-header">
											<h1 class="modal-title fs-5" id="staticBackdropLabel">Detalhes de {{ cli.nome }}</h1>
											<button type="button" class="btn-close text-secondary" data-bs-dismiss="modal" aria-label="Close" style="font-size:2rem;">&times;</button>
										</div>
										<div class="modal-body">
											<div class="row">
												<div class="col-12">
													<div class="card">
														<div class="list-group overflow-auto" style="text-align:left; max-height: 200px;">
															<h5>Projetos: {{cli.projetos|length}}</h5>
															
															{% for proj in cli.projetos %}
															<ul  style="margin-left:-32px;">
																<li class="list-group-item mb-1">
																	<span class="mx-2">{{ proj.titulo }}</span>
																	<span class="badge badge-sm text-xxs bg-gradient-{%if proj.status == 'iniciado'%}info{%elif proj.status == 'em atraso'%}danger{%elif proj.status == 'cancelado'%}primary{%elif proj.status == 'congelado'%}secondary{%else%}success{%endif%}">{{ proj.status }}</span>
																</li>
															</ul>
															{% endfor %}
														</div>
											
														<hr class="dark horizontal my-0">
											
														<div class="mt-2">
															<h5>Dados pessoais</h5>
															
															<ul class="list-group"  style="text-align:left;">
																<li class="list-group-item"><strong class="text-secondary">Nome: </strong>{{cli.nome}}</li>
																<li class="list-group-item"><strong class="text-secondary">Email: </strong>{{cli.email}}</li>
																<li class="list-group-item"><strong class="text-secondary">Fone: </strong>{{cli.fone}}</li>
																<li class="list-group-item"><strong class="text-secondary">CPF/CNPJ: </strong>{{cli.cpf_cnpj}}</li>
																<li class="list-group-item"><strong class="text-secondary">Logra: </strong>{{cli.logradouro}}</li>
																<li class="list-group-item"><strong class="text-secondary">CEP: </strong>{{cli.cep}}</li>
																<li class="list-group-item"><strong class="text-secondary">Bairro: </strong>{{cli.bairro}}</li>
																<li class="list-group-item"><strong class="text-secondary">Comp: </strong>{{cli.complemento}}</li>
																<li class="list-group-item"><strong class="text-secondary">Cidade: </strong>{{cli.cidade}}</li>
																<li class="list-group-item"><strong class="text-secondary">Estado: </strong>{{cli.uf}}</li>
																<li class="list-group-item"><strong class="text-secondary">Status: </strong><span class="badge badge-sm bg-gradient-{%if cli.status == 'regular'%}success{%else%}warning{%endif%}">{{cli.status}}</span></li>
															</ul>
														</div>
													</div>
												</div>
											</div>
											
											<div class="modal-footer">
												<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
												<a href="{{ url_for('cliente.delete', id_cliente=cli.id_cliente) }}" class="btn btn-danger" onclick="return confirm('Todos os projetos deste cliente também serão excluídos, deseja continuar?')">Eliminar</a>
											</div>
										</div>
									</div>
								</div>
							</div>
						{% endfor %}
					  </tbody>
					</table>
					{% endif %}
				</div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

templates/lista_projetos.html
{% extends "base.html" %}

{% block content %}

		{% if request.args["msg"] %}
		<div class="alert alert-{{request.args['alert']}} alert-dismissible text-white opacity-8" role="alert">
			<span class="text-sm">{{request.args["msg"]}}</span>
			<button type="button" class="btn-close text-lg py-3 opacity-10" data-bs-dismiss="alert" aria-label="Close">
			  <span aria-hidden="true">&times;</span>
			</button>
		</div>
		{% endif %}
		
      <div class="row">
        <div class="col-12">
          <div class="card my-4">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <div class="bg-gradient-dark shadow-dark border-radius-lg pt-4 pb-3">
                <h6 class="text-white text-capitalize ps-3">Exibe 10 registros por página</h6>
              </div>
            </div>
            <div class="card-body px-0 pb-2">
              <div class="table-responsive p-0 text-center">
				  
				{% if projetos|length == 0 %}
				<h6 class="text-secondary">Não há nada a exibir ainda, clique no botão para inserir</h6>
				<a href="{{url_for('projeto.form_novo_projeto')}}" class="btn btn-info">iniciar projeto</a>
				{% else %}
			
                <table class="table align-items-center mb-0">
                  <thead>
                    <tr>
                      <th class="text-uppercase text-secondary text-s font-weight-bolder opacity-7">ID</th>
                      <th class="text-uppercase text-secondary text-s font-weight-bolder opacity-7">Projeto</th>
                      <th class="text-uppercase text-secondary text-s font-weight-bolder opacity-7 ps-2">Serviço</th>
                      <th class="text-center text-uppercase text-secondary text-s font-weight-bolder opacity-7">Status</th>
                      <th class="text-center text-uppercase text-secondary text-s font-weight-bolder opacity-7">Ações</th>
                    </tr>
                  </thead>
                  <tbody>
					{% for proj in projetos %}
                    <tr>
						<td>
							<div class="d-flex justify-content-center">
								<div class=" d-flex flex-column justify-content-center">
									<h6 class="mb-0 text-s">{{ proj.id_projeto }}</h6>
								</div>
							</div>
						</td>
						<td>
							<div class="d-flex justify-content-center">
								<div class="d-flex flex-column">
								<h6 class="mb-0 text-s">{{ proj.titulo }}</h6>
								<p class="text-sm text-secondary mb-0">{{ proj.cliente.nome }}</p>
								</div>
							</div>
						</td>
						<td>
							<p class="text-s font-weight-bold mb-0">{{ proj.tipo }}</p>
							<p class="text-sm text-secondary mb-0">{{ proj.tecnologia }}</p>
						</td>
						<td class="align-middle text-center text-sm">
							<span class="badge badge-sm bg-gradient-{%if proj.status == 'iniciado'%}info{%elif proj.status == 'em atraso'%}danger{%elif proj.status == 'cancelado'%}primary{%elif proj.status == 'congelado'%}secondary{%else%}success{%endif%}">{{ proj.status }}</span>
						</td>
						<td class="align-middle text-center">
							<a href="{{ url_for('projeto.form_editar_projeto', id_projeto=proj.id_projeto) }}" title="Alterar dados">
								<span class="material-symbols-outlined text-dark text-lg">edit_square</span>
							</a>
							<span class="material-symbols-outlined text-info text-lg" data-bs-toggle="modal" data-bs-target="#staticBackdrop{{proj.id_projeto}}" style="cursor:pointer;" title="Ver detalhes">visibility</span>
						</td>
                    </tr>

				<!-- Modal -->
				<div class="modal fade" id="staticBackdrop{{proj.id_projeto}}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
					<div class="modal-dialog">
						<div class="modal-content">
							<div class="modal-header">
								<h1 class="modal-title fs-5" id="staticBackdropLabel">Detalhes do projeto</h1>
								<button type="button" class="btn-close text-secondary " data-bs-dismiss="modal" aria-label="Close" style="font-size:2rem;">&times;</button>
							</div>
							<div class="modal-body">
								<div class="row">
									<div class="col-12">
										<div class="card">
											
											<div class="" style="text-align:left;">
												
												<ul class="list-group text-left">
													<li class="list-group-item"><strong class="text-secondary">Solicitante: </strong>{{proj.cliente.nome}}</li>
													<li class="list-group-item"><strong class="text-secondary">Tipo: </strong>{{proj.tipo}}</li>
													<li class="list-group-item"><strong class="text-secondary">Tecnologia: </strong>{{proj.tecnologia}}</li>
													<li class="list-group-item"><strong class="text-secondary">Descrição: </strong>{{proj.detalhes}}</li>
													<li class="list-group-item"><strong class="text-secondary">Valor: </strong>{{proj.valor}}</li>
													<li class="list-group-item"><strong class="text-secondary">Pagamento via: </strong>{{proj.metodo_pag}}</li>
													<li class="list-group-item"><strong class="text-secondary">Entrega em: </strong>{{proj.data_entrega}}</li>
													<li class="list-group-item"><strong class="text-secondary">Status: </strong><span class="badge badge-sm bg-gradient-{%if proj.status == 'iniciado'%}info{%elif proj.status == 'em atraso'%}danger{%elif proj.status == 'cancelado'%}primary{%elif proj.status == 'congelado'%}secondary{%else%}success{%endif%}">{{ proj.status }}</span></li>
												</ul>
											</div>
										</div>
									</div>
							  </div>
						  
							  <div class="modal-footer">
								<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
								<a href="{{ url_for('projeto.delete', id_projeto=proj.id_projeto) }}" class="btn btn-danger" onclick="return confirm('Deseja mesmo excluir este projeto?')">Eliminar</a>
							  </div>
						  
							</div>
						</div>
					</div>
				</div>
				{% endfor %}
                  </tbody>
                </table>
			  {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>

{% endblock %}

templates/novo_cliente.html
{% extends "base.html" %}

{% block content %}

              
	<div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
		
		{% if request.args["msg"] %}
		<div class="alert alert-{{request.args['alert']}} alert-dismissible text-white" role="alert">
			<span class="text-sm">{{request.args["msg"]}}</span>
			<button type="button" class="btn-close text-lg py-3 opacity-10" data-bs-dismiss="alert" aria-label="Close">
			  <span aria-hidden="true">&times;</span>
			</button>
		</div>
		{% endif %}
		
		
          <div class="card mt-4">
             <div class="col-xl-10 col-lg-5 col-md-7 d-flex flex-column ms-auto me-auto ms-lg-auto me-lg-5">
              <div class="card card-plain">
                <div class="card-header">
                  <h4 class="font-weight-bolder">Registrar cliente</h4>
                  <p class="mb-0">Certifique-se de preencher atentamente todos os campos</p>
                </div>
                <div class="card-body">
                  <form role="form" action="{{url_for('cliente.cadastra_cliente')}}" method="POST">
                    <div class="input-group input-group-outline mb-3">
                      <label class="form-label">Nome*</label>
                      <input type="text" name="nome" class="form-control" required>
                    </div>
                    <div class="input-group input-group-outline mb-3">
                      <label class="form-label">Email*</label>
                      <input type="email" name="email" class="form-control" required>
                    </div>
                    <div class="input-group input-group-outline mb-3">
                      <label class="form-label">Telefone*</label>
                      <input type="phone" name="fone" class="form-control" required>
                    </div>
                    <div class="input-group input-group-outline mb-3">
                      <label class="form-label">CPF/CNPJ*</label>
                      <input type="text" name="cpf_cnpj" class="form-control" required>
                    </div>
                    <div class="form-check form-check-info text-start ps-0">
                      <label class="form-check-label" for="flexCheckDefault">
                      <p class="text-dark font-weight-bolder">Preencha o endereço</p>
                      </label>
                    </div>
                    <div class="input-group input-group-outline mb-3">
                      <label class="form-label">Logradouro*</label>
                      <input type="text"  name="logra" class="form-control" required>
                    </div>
                    <div class="input-group input-group-outline mb-3">
                      <label class="form-label">CEP*</label>
                      <input type="text" name="cep" class="form-control" required>
                    </div>
                    <div class="input-group input-group-outline mb-3">
                      <label class="form-label">Bairro*</label>
                      <input type="text" name="bairro" class="form-control" required>
                    </div>
					<div class="input-group input-group-outline mb-3">
                      <label class="form-label">Complemento*</label>
                      <input type="text" name="comple" class="form-control" required>
                    </div>
					<div class="input-group input-group-outline mb-3">
                      <label class="form-label">Cidade*</label>
                      <input type="text" name="cidade" class="form-control" required>
                    </div>
                    <div class="input-group input-group-outline mb-3">
                      <select class="form-control" name="uf" required>
						<option value="">Selecione um estado</option>
						<option value="AC">Acre</option>
						<option value="AL">Alagoas</option>
						<option value="AP">Amapá</option>
						<option value="AM">Amazonas</option>
						<option value="BA">Bahia</option>
						<option value="CE">Ceará</option>
						<option value="DF">Distrito Federal</option>
						<option value="ES">Espírito Santo</option>
						<option value="GO">Goiás</option>
						<option value="MA">Maranhão</option>
						<option value="MT">Mato Grosso</option>
						<option value="MS">Mato Grosso do Sul</option>
						<option value="MG">Minas Gerais</option>
						<option value="PA">Pará</option>
						<option value="PB">Paraíba</option>
						<option value="PR">Paraná</option>
						<option value="PE">Pernambuco</option>
						<option value="PI">Piauí</option>
						<option value="RJ">Rio de Janeiro</option>
						<option value="RN">Rio Grande do Norte</option>
						<option value="RS">Rio Grande do Sul</option>
						<option value="RO">Rondônia</option>
						<option value="RR">Roraima</option>
						<option value="SC">Santa Catarina</option>
						<option value="SP">São Paulo</option>
						<option value="SE">Sergipe</option>
						<option value="TO">Tocantins</option>
					  </select>
                    </div>
					
					<!-- CAMPO STATUS OCULTO-->
					<input type="hidden" name="status" value="regular">
					
                    <div class="text-center">
                      <button type="submit" class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0">Cadastrar</button>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>  
		  
		  
		  
          
	</div>
{% endblock %}